<?php

abstract class BookAbstract
{
    protected $name;
    protected $author;

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }
}

abstract class FactoryAbstract
{
    public abstract function getBook();
}

class PhpBook extends BookAbstract
{
    public function getName()
    {
        return "PHP book"; // TODO: Change the autogenerated stub
    }

    public function getAuthor()
    {
        return "Mat Zandstra"; // TODO: Change the autogenerated stub
    }
}

class MysqlBook extends BookAbstract
{
    public function getName()
    {
        return "mysql book"; // TODO: Change the autogenerated stub
    }

    public function getAuthor()
    {
        return "mysql author"; // TODO: Change the autogenerated stub
    }
}

class PhpBookFactory extends FactoryAbstract
{
    public function getBook()
    {
        return new PhpBook();
    }
}

class MysqlBookFactory extends FactoryAbstract
{
    public function getBook()
    {
        return new MysqlBook();
    }
}


$php = new PhpBookFactory();
$mysql = new MysqlBookFactory();

$bookm = $mysql->getBook();
echo $bookm->getAuthor();
echo $bookm->getName();